_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 32
dropout:
    value: 0.2
event_weight:
    value: 3
hidden_dim:
    value: 64
learning_rate:
    value: 0.001
model_type:
    value: ResponsiveWinPredictor
num_layers:
    value: 2
weight_decay:
    value: 1e-05
